### ISSUE TITLE
unhandled exception when running 'cafe chef download' (w/o specifying version)

### ISSUE THREAD

**Issue by finam** [mhedgpeth/cafe#11]
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at cafe.CommandLine.OptionGroup.Run(Argument[] args) in C:\code\community\cafe\src\cafe\CommandLine\OptionGroup.cs:line 112
   at cafe.CommandLine.OptionGroup.RunProgram(Argument[] arguments) in C:\code\community\cafe\src\cafe\CommandLine\OptionGroup.cs:line 68
   at cafe.Program.Main(String[] args) in C:\code\community\cafe\src\cafe\Program.cs:line 40

Should it download the newest version by default, or just fail more gracefully?

**Comment by mhedgpeth** [comment]
Thanks @finam for the submission. This is fixed in #12 and will be released as a part of 0.5.2
